### PR TITLE
Improve PHPStan configuration

### PR DESCRIPTION
**Pull request by szepeviktor**
- Add WC Subscriptions
- Lower level to 0

### CODE REVIEW

**Comment by szepeviktor** [comment]
There are

> [ERROR] Found 7 errors

**Comment by seebeen** [comment]
Awesome work.

**Comment by szepeviktor** [comment]
Glad to contribute.

**Comment by szepeviktor** [comment]
@seebeen Do you have someone to work on discovered problems or may I work on it?

**Comment by seebeen** [comment]
What do you have in mind? :)

**Comment by szepeviktor** [comment]
Currently on level 0 there are 7 errors.

There should be zero on level 5.

**Comment by seebeen** [comment]
Understood. Feel free to solve them if you have the time. 💪💪💪💪

**Pull request merged**
